import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { TaskProvider } from "@/context/TaskContext";
import Link from "next/link";
import SignIn from "@/components/auth/SignIn";
import { SignOut } from "@/components/auth/SignOut";
import { auth } from "@/auth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "To-do List",
  description: "Generated by crombie",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth()

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="flex justify-between p-4 bg-gray-800 text-white font-bold">
          <Link href="/">Home</Link>
          <Link href="/tasks">Tasks</Link>
          {session ?
            <SignOut /> :
            <SignIn />
          }
        </nav>
        <TaskProvider>
          {children}
        </TaskProvider>
      </body>
    </html>
  );
}
